### ISSUE TITLE
Nejdou mi napsat komentáře

### ISSUE THREAD

**Issue by LucieKULHAVA** [LenkaSilna/piskvorky#1]
https://github.com/LenkaSilna/piskvorky/blob/3f5837b1ec6e88c432c8080328eba0b6f8accb44/pravidla.html#L120

Ahoj Leni, podle mne moc pěkný kod, jen mi do něj nejdou napsat komentáře, které bych tedy ani stejně neměla :-)

**Comment by LenkaSilna** [comment]
Ahoj, moc děkuji za code review i za komentář. Potěšil.
